# Generated by Django 3.1.4 on 2021-01-20 20:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    replaces = [('mainapp', '0001_initial'), ('mainapp', '0002_auto_20201214_2001'), ('mainapp', '0003_auto_20201217_2041'), ('mainapp', '0004_auto_20210101_2105'), ('mainapp', '0005_auto_20210110_1749'), ('mainapp', '0006_auto_20210110_1837'), ('mainapp', '0007_auto_20210111_2001'), ('mainapp', '0008_comment_revised'), ('mainapp', '0009_auto_20210114_2027')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='updated_at')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(default='1@get.com', max_length=40, verbose_name='email')),
                ('first_name', models.CharField(default='First name', max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(default='Last name', max_length=32, verbose_name='Last name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=400, verbose_name='content')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Responce',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=400, verbose_name='content')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
                ('revised', models.BooleanField(default=False, verbose_name='revised')),
            ],
        ),
    ]
