# Generated by Django 3.1.2 on 2020-10-21 20:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 14, 17, 924711))),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Responces',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 14, 17, 925486))),
                ('deleted_at', models.DateTimeField(null=True)),
                ('autor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='380671234567', max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12)])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 14, 17, 926136))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 14, 17, 926159))),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='autor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 14, 17, 923513))),
                ('deleted_at', models.DateTimeField(null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user')),
            ],
        ),
    ]
