# Generated by Django 3.1.2 on 2020-10-31 20:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=400, verbose_name='content')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='User_agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responces',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('autor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user_agent')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(default='380671234567', max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12)], verbose_name='phone')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted _at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user_agent')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='autor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user_agent'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.TextField(max_length=400, verbose_name='content')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user_agent')),
            ],
        ),
    ]
