# Generated by Django 3.1.2 on 2020-11-11 21:00

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    replaces = [('mainapp', '0001_initial'), ('mainapp', '0002_auto_20201107_1851'), ('mainapp', '0003_auto_20201108_2048'), ('mainapp', '0004_auto_20201111_1937')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=400, verbose_name='content')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12)], verbose_name='phone')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='updated_at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.TextField(max_length=400, verbose_name='content')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.profile'),
        ),
        migrations.CreateModel(
            name='Responce',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='created_at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted_at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.product')),
            ],
        ),
    ]
