# Generated by Django 3.1.2 on 2020-11-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='autor_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='responce',
            old_name='autor_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='responce',
            old_name='product_id',
            new_name='product',
        ),
    ]
