    # Generated by Django 3.1.2 on 2020-11-11 19:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201108_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='responce',
            old_name='autor',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12)], verbose_name='phone'),
        ),
    ]
