# Generated by Django 3.1.4 on 2021-01-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201217_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='1@get.com', max_length=40, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='First name', max_length=32, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Last name', max_length=32, verbose_name='Last name'),
        ),
    ]
