# Generated by Django 3.1.4 on 2021-01-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210111_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='revised',
            field=models.BooleanField(default=True, verbose_name='revised'),
        ),
    ]
